version: "3"
services:
    stock:
        build: ./
        #image: pythonstock/pythonstock:base-2021-03
        container_name: mystock
        ports:
            - "8888:8888"
            - "9999:9999"
        volumes:
            - "./data/notebooks:/data/notebooks"
            - "./data/logs:/data/logs"
            - "./jobs:/data/stock/jobs"
            - "./libs:/data/stock/libs"
            - "./web:/data/stock/web"
        environment:
            MYSQL_HOST: mysqldb
            MYSQL_USER: root
            MYSQL_PWD: mysqldb
            MYSQL_DB: stock_data
            LANG: zh_CN.UTF-8
            LC_CTYPE: zh_CN.UTF-8
            PYTHONIOENCODING: utf-8
            # 测试使用，自己需注册，申请：https://tushare.pro/user/token
            TUSHARE_TOKEN: 9a742f208532e6301ceb4ddca014e85517c96cdeb7c7d3afa9fe7cf3
        links:
            - mysqldb:mysqldb
        restart: always
    mysqldb:
        image: mysql:5.7
        container_name: mysqldb
        ports:
            - "3306:3306"
        volumes:
            - "./data/mysqldb/data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: mysqldb
            MYSQL_DATABASE: stock_data
            TZ: Asia/Shanghai
        restart: always
        
